### ISSUE TITLE
searchLunrish appears to fail if searches are made outside of the /search context (e.g. landing page or page/post page)

### ISSUE THREAD

**Issue by danielsgriffin** [danielsgriffin/.com#1]
autocomplete.js:66 Server-side search failed: ReferenceError: searchLunrish is not defined
    at generateNewCombinedSuggestions (autocomplete.js:36:35)
    at HTMLInputElement.<anonymous> (autocomplete.js:142:47)

**Comment by danielsgriffin** [comment]
Fixed.
Searched for where js/search/lunrish.js was used: rg "lunrish.js"
Then moved it out of a check for the /search so it loads on all pages.
